filebeat.inputs:
- type: filestream    
  enabled: true
  fields:
    type: "name"
  paths:
    - /logs/app.log
  exclude_lines: ['^\\s*$']
  parsers:
  - multiline:
     type: pattern
     pattern: '^INFO\s+\| jvm 1\s+\| [0-9]{4}\/[0-9]{2}\/[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3} \| \['
     negate: true
     match: after

# ======================= Elasticsearch template setting =======================

setup.template.settings:
  index.number_of_shards: 1
  #index.codec: best_compression
  #_source.enabled: false

setup.ilm.enabled: false
setup.template.name: "lab-%{[fields.type]:other}"
setup.template.pattern: "lab-%{[fields.type]:other}-*"

# ---------------------------- Elasticsearch Output ----------------------------
output.elasticsearch:
  # Array of hosts to connect to.
  hosts: '${ES_HOST:localhost:9200}'
  protocol: '${ES_PROTOCOL:http}'
  index: "lab-%{[fields.type]:other}"
  username: '${ES_USERNAME:elastic}'
  password: '${ES_PASSWORD:changeme}'

# ================================= Processors =================================
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
