server:
  port: 9000

opentracing:
  jaeger:
    http-sender:
      url: http://localhost:14268/api/traces
    udp-sender:
      host: localhost
      port: 6831
    log-spans: true

spring:
  profiles:
    active: dev

  application:
    name: animal-generator

logging:
  level:
    io:
      jaegertracing: DEBUG
#  file:
#    name: /dev/github/lab-observability/logs/ms-animal.log

application:
  elk:
    protocol: ${ES_PROTOCOL:http}
    url: ${ES_HOST:localhost}
    port: ${ES_PORT:9200}
    user: ${ES_USER:elastic}
    pwd: ${ES_PWD:changeme}