server:
  port: 9000

opentracing:
  jaeger:
    http-sender:
      url: http://localhost:14268/api/traces
    udp-sender:
      host: localhost
      port: 6831
    log-spans: true

spring:
  profiles:
    active: dev

  application:
    name: animal-generator