version: "3.4"
services:
  # animal-name-service:
  #   image: com.example/animal-name-service:0.1.0
  #   restart: on-failure
  #   environment:
  #     - SPRING_PROFILES_ACTIVE=prod
  #     - SPRING_APPLICATION_NAME=animal-name-service
  # scientist-name-service:
  #   image: com.example/scientist-name-service:0.1.0
  #   restart: on-failure
  #   environment:
  #     - SPRING_PROFILES_ACTIVE=prod
  #     - SPRING_APPLICATION_NAME=scientist-name-service
  # name-generator-service:
  #   image: com.example/name-generator-service:0.1.0
  #   restart: on-failure
  #   environment:
  #     - SPRING_PROFILES_ACTIVE=prod
  #     - SPRING_APPLICATION_NAME=name-generator-service
  #   ports:
  #     - "8080:8080"
  jaeger:
    image: jaegertracing/all-in-one:1.25
    ports:
      - 9090:16686
      - 6831:6831/udp
      - 6832:6832/udp
      - 16686:16686
      - 14268:14268

  es01:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
        container_name: es01
        environment:
            - discovery.type=single-node
            - node.name=es01
            - cluster.name=es-docker-cluster
            #- cluster.initial_master_nodes=es01
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - ./es01:/usr/share/elasticsearch/data
        ports:
            - 9200:9200

  kibana:
      image: docker.elastic.co/kibana/kibana:7.11.2
      container_name: kibana
      ports:
          - 5601:5601
      environment:
          ELASTICSEARCH_URL: http://es01:9200
          ELASTICSEARCH_HOSTS: '["http://es01:9200"]'